[package]
name = "sys"
version = "0.1.0"
authors = ["yinjian"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
chrono = "0.4.38"
sysinfo = "0.32.0"
termion = "4.0.3"
