[package]
name = "jterm"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.153"
nix = {version = "0.28.0", features = ["term", "ioctl", "fs"]}
rustix = "0.38.31"
x11 = {version = " 2.21.0", features = ["xlib"]}
