[package]
name = "relm_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = "0.9.1"
relm4-macros = "0.9.1"

battery = "0.7.8"
flexi_logger = { version = "0.31.2", features = ["colors"] }
glib = "0.20.12"
gtk4 = { version = "0.9.7", features = ["v4_14"] }
log = "0.4.27"
sysinfo = "0.35.2"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.23"
shared_structures = { path = "../shared_structures" }
chrono = "0.4.41"
cairo-rs = "0.20.12"
pango = "0.20.12"
once_cell = "1.21.3"
alsa = "0.9.1"
gdk4-x11 = { version = "0.9.6", features = ["xlib"] }
gdk4 = { version = "0.9.6", features = ["v4_14"] }
glib-build-tools = "0.21.0"
adw = { version = "0.7.2", package = "libadwaita", features = ["v1_5"] }
relm4-components = "0.9.1"
tracker = "0.2.2"
