[package]
name = "jterm4"
version = "0.1.0"
edition = "2021"

[dependencies]
gdk4 = { version = "0.9.2", features = ["v4_14"] }
gtk4 = "0.9.2"
pango = "0.20.4"
pcre2 = "0.2.9"
pcre2-sys = "0.2.9"
vte4 = { version = "0.8.0", features = ["v0_74"] }
