[package]
name = "bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo = "0.0.4"
pango = "0.20.4"
pangocairo = "0.20.4"
x11 = "2.21.0"

