[package]
name = "shared_structures"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.7.0"
log = "0.4.26"
nix = { version = "0.30.1", features = ["event", "fs"] }
serde = { version = "1.0.217", features = ["derive"] }
shared_memory = "0.12.4"

[[bench]]
name = "ring_buffer_bench"
harness = false
