[package]
name = "jwm"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.158"
log = "0.4.22"
once_cell = "1.19.0"
simplelog = "0.12.2"
x11 = "2.21.0"
# x11 = { version = "2.21.0", features = ["all"] }
yeslogic-fontconfig-sys = "6.0.0"
