[package]
name = "jwm"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[dependencies]
# alsa = "0.9.1"
battery = "0.7.8"
bincode = "1.3.3"
# cairo-rs = { version = "0.20.5", features = ["xlib"]}
chrono = "0.4.38"
coredump = "0.1.2"
dirs-next = "2.0.0"
flexi_logger = "0.29.8"
lazy_static = "1.5.0"
libc = "0.2.158"
log = "0.4.22"
nix = { version = "0.30.1", features = ["signal"] }
once_cell = "1.19.0"
# pango = { version = "0.20.4", features = ["v1_44"]}
# pangocairo = "0.20.4"
rand = "0.8.5"
regex = "1.11.0"
serde = { version = "1.0.217", features = ["derive"] }
shared_memory = "0.12.4"
shared_structures = { version = "0.1.0", path = "../shared_structures" }
sysinfo = "0.32.0"
x11 = { version = "2.21.0", features = ["all"] }
yeslogic-fontconfig-sys = "6.0.0"

[build-dependencies]
bindgen = "0.70.1"
pkg-config = "0.3"
