[package]
name = "jwm"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[features]
default = []
egui_bar = []
iced_bar = []
dioxus_bar = []
tauri_bar = []
gtk_bar = []
relm_bar = []
nixgl = []
cairo = []

[[bin]]
name = "jwm_test"
path = "tests/integration_test.rs"

[[bin]]
name = "slotmap_test"
path = "tests/slot_map_test.rs"

[[bin]]
name = "jwm-tool"
path = "tools/jwm_tool.rs"

[dependencies]
battery = "0.7.8"
bincode = "1.3.3"
cfg-if = "1.0.1"
chrono = "0.4.38"
clap = { version = "4.5.45", features = ["derive", "env"] }
coredump = "0.1.2"
criterion = "0.7.0"
dirs = "6.0.0"
dirs-next = "2.0.0"
fastrand = "2.3.0"
flexi_logger = "0.29.8"
glob = "0.3.3"
lazy_static = "1.5.0"
libc = "0.2.158"
log = "0.4.22"
nix = { version = "0.30.1", features = ["signal"] }
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.11.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.143"
shared_memory = "0.12.4"
shared_structures = { path = "../shared_structures", features = ["use-eventfd"] }
# shared_structures = { path = "../shared_structures", features = ["use-semaphore"] }
# shared_structures = { path = "../shared_structures", features = ["use-futex"] }
signal-hook = "0.3.18"
slotmap = { version = "1.0.7", features = ["serde"] }
sysinfo = "0.32.0"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
x11 = { version = "2.21.0", features = ["all"] }
x11rb = { version = "0.13.1", features = ["all-extensions"] }
x11rb-protocol = "0.13.1"

[build-dependencies]
bindgen = "0.70.1"
pkg-config = "0.3"

[[bench]]
name = "wm_benchmark"
harness = false
