[package]
name = "jwm"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[dependencies]
alsa = "0.9.1"
battery = "0.7.8"
chrono = "0.4.38"
lazy_static = "1.5.0"
libc = "0.2.158"
log = "0.4.22"
once_cell = "1.19.0"
pango = { version = "0.20.4", features = ["v1_44"]}
regex = "1.11.0"
simplelog = "0.12.2"
sysinfo = "0.32.0"
x11 = { version = "2.21.0", features = ["all"] }
yeslogic-fontconfig-sys = "6.0.0"
