[package]
name = "jwm"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[features]
default = []
egui_bar = []
iced_bar = []
dioxus_bar = []
tauri_bar = []
gtk_bar = []
relm_bar = []
nixgl = []
cairo = []

[dependencies]
battery = "0.7.8"
bincode = "1.3.3"
cfg-if = "1.0.1"
chrono = "0.4.38"
coredump = "0.1.2"
dirs = "6.0.0"
dirs-next = "2.0.0"
flexi_logger = "0.29.8"
lazy_static = "1.5.0"
libc = "0.2.158"
log = "0.4.22"
nix = { version = "0.30.1", features = ["signal"] }
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.11.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.143"
shared_memory = "0.12.4"
# shared_structures = { path = "../shared_structures", features = ["use-eventfd"] }
shared_structures = { path = "../shared_structures", features = ["use-semaphore"] }
slotmap = { version = "1.0.7", features = ["serde"] }
sysinfo = "0.32.0"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
x11 = { version = "2.21.0", features = ["all"] }
x11rb = { version = "0.13.1", features = ["all-extensions"] }
x11rb-protocol = "0.13.1"
# yeslogic-fontconfig-sys = "6.0.0"

[build-dependencies]
bindgen = "0.70.1"
pkg-config = "0.3"
