# config.toml
[appearance]
border_px = 3
snap = 32
dmenu_font = "SauceCodePro Nerd Font Regular 11"
status_bar_pad = 5
broken = "broken"

[behavior]
focus_follows_new_window = false
resize_hints = true
lock_fullscreen = true

[status_bar]
name = "egui_bar"
bar_0 = "egui_bar_0"
bar_1 = "egui_bar_1"

[colors]
dark_sea_green1 = "#afffd7"
dark_sea_green2 = "#afffaf"
pale_turquoise1 = "#afffff"
light_sky_blue1 = "#afd7ff"
grey84 = "#d7d7d7"
cyan = "#00ffd7"
white = "#ffffff"
black = "#000000"
transparent = 0
opaque = 255

[layout]
m_fact = 0.55
n_master = 1
tags_length = 9

[keybindings]
modkey = "Mod1"

[[keybindings.keys]]
modifier = ["Mod1"]
key = "e"
function = "spawn"
argument = ["dmenu_run", "-m", "0", "-fn", "SauceCodePro Nerd Font Regular 11", "-nb", "#afd7ff", "-nf", "#afffff", "-sb", "#000000", "-sf", "#d7d7d7", "-b"]

[[keybindings.keys]]
modifier = ["Mod1", "Shift"]
key = "Return"
function = "spawn"
argument = ["x-terminal-emulator"]

[[keybindings.keys]]
modifier = ["Mod1"]
key = "j"
function = "focusstack"
argument = 1

[[keybindings.keys]]
modifier = ["Mod1"]
key = "k"
function = "focusstack"
argument = -1

# 更多按键绑定...

[mouse_bindings]

[[mouse_bindings.buttons]]
click_type = "ClkLtSymbol"
modifier = []
button = 1
function = "setlayout"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkClientWin"
modifier = ["Mod1"]
button = 1
function = "movemouse"
argument = 0

# 更多鼠标绑定...

[[rules]]
class = "broken"
instance = "broken"
name = "broken"
tags_mask = 0
is_floating = true
monitor = -1

[[rules]]
class = "egui_bar_0"
instance = "egui_bar_0"
name = "egui_bar"
tags_mask = 511  # (1 << 9) - 1
is_floating = true
monitor = 0

# config.toml 中的鼠标绑定部分
[mouse_bindings]

[[mouse_bindings.buttons]]
click_type = "ClkLtSymbol"
modifier = []
button = 1
function = "setlayout"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkLtSymbol"
modifier = []
button = 3
function = "setlayout"
argument = "monocle"

[[mouse_bindings.buttons]]
click_type = "ClkWinTitle"
modifier = []
button = 2
function = "zoom"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkStatusText"
modifier = []
button = 2
function = "spawn"
argument = ["x-terminal-emulator"]

[[mouse_bindings.buttons]]
click_type = "ClkClientWin"
modifier = ["Mod1"]
button = 1
function = "movemouse"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkClientWin"
modifier = ["Mod1"]
button = 2
function = "togglefloating"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkClientWin"
modifier = ["Mod1"]
button = 3
function = "resizemouse"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkTagBar"
modifier = []
button = 1
function = "view"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkTagBar"
modifier = []
button = 3
function = "toggleview"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkTagBar"
modifier = ["Mod1"]
button = 1
function = "tag"
argument = 0

[[mouse_bindings.buttons]]
click_type = "ClkTagBar"
modifier = ["Mod1"]
button = 3
function = "toggletag"
argument = 0