[package]
name = "toy"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", features = ["glow", "wgpu"] }
egui = "0.29.1"
env_logger = "0.11.5"
regex = "1.11.1"
ssh2 = "0.9.4"
