[package]
name = "clock"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = "0.4"
tracing-subscriber = "0.3"
iced_aw = "0.12.2"
iced = { version = "0.13.1", features = ["advanced", "async-std", "canvas", "debug", "lazy", "tokio"] }
log = "0.4.27"
