[package]
name = "iced_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
flexi_logger = "0.31.0"
iced = { version = "0.13.1", features = ["advanced", "async-std", "canvas", "debug", "lazy", "tokio"] }
iced_aw = "0.12.2"
iced_fonts = { version = "0.2.1", features = ["full"] }
log = "0.4.27"
thiserror = "2.0.12"
toml = "0.8.23"
shared_structures = { path = "../shared_structures" }
time = "0.3.41"
tokio = { version = "1.45.1", features = ["full", "time"] }
iced_futures = { version = "0.13.2", features = ["tokio"] }
sysinfo = "0.35.2"
battery = "0.7.8"
alsa = "0.9.1"
iced_glow = "0.8.0"
