[package]
name = "tgit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coredump = "0.1.2"
substring = "1.4.5"
termion = "2.0.1"
